server.port=8081
spring.datasource.url=jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.main.allow-bean-definition-overriding=true
#springdoc.swagger-ui.path=/swagger-ui/index.html
#springdoc.swagger-ui.operationsSorter=method
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.version=4.1.3
logging.level.org.springframework=INFO
payment.service.url=http://localhost:8082
